### ISSUE TITLE
The node which belongs to NodeTypeEnd should refuse the requests to apply event.

### ISSUE THREAD

**Issue by zhushh** [js-ojus/flow#115]
Hi, I think the node should refuse the request to apply event if it is in NodeTypeEnd. How do you think so?

the code:
```go
func (n *Node) applyEvent(otx *sql.Tx, event *DocEvent, recipients []GroupID) (DocStateID, error) {
    ...
    switch tnode.NodeType {
    ...
    case NodeTypeBegin, NodeTypeEnd, NodeTypeLinear, NodeTypeBranch:
        ....
    }
}
```

**Comment by js-ojus** [comment]
@zhushh 

`tnode` is the target node, i.e. the node that this document shall reach by applying the given event.  It does _not_ correspond to the current document state.  It corresponds to the _next_ document state.

Accordingly, it should still record the application of the event, and dispatch notifications.

**Comment by zhushh** [comment]
Oh, sorry. What I mean is if the node is NodeTypeEnd, then it can not call applyEvent function.
The code is:
```go
func (w *Workflow) ApplyEvent(otx *sql.Tx, event *DocEvent, recipients []GroupID) (DocStateID, error) {
    ...
    nstate, err := n.applyEvent(tx, event, recipients)
    if err != nil {
        return 0, err
    }
    ...
}
```

**Comment by js-ojus** [comment]
@zhushh 

`NodeTypeEnd` should process `applyEvent`, because we still have to notify applicable users that the document has transitioned to the `DocState` corresponding to this end node.  These notifications are sent in `applyEvent`.

Once the document transitions into this final state, there are no more possible state transitions.  Therefore, we cannot create an event on this document any longer.  And therefore, `applyEvent` shall never be called again.

Or, have I not yet understood your question?!

**Comment by zhushh** [comment]
@js-ojus 

So, what is the purpose of node type? I mean you design nodeType for node, but it is not useful currently. Right?

**Comment by js-ojus** [comment]
@zhushh 

Yes, you are correct that it is not useful currently.  It becomes useful once `NodeTypeJoinAll` is implemented.  [_I am working on that in the next version._]

**Comment by zhushh** [comment]
OK. Thanks~
