### ISSUE TITLE
Adding a group to Access Context should include all the group users

### ISSUE THREAD

**Issue by sandeepguntaka** [js-ojus/flow#30]
When a group is added to an access context it would be good to have a method which returns all the group members of that access context.

**Comment by js-ojus** [comment]
Currently, since reporting hierarchy is tracked at an individual user level, this change mandates that we use the same reporting authority for all users of the group.

Now, suppose that another group is also added to this access context, with a different reporting authority.  Further suppose that there is a common user in both groups.  Which of the reporting authorities should reflect in the table `wf_ac_user_hierarchy`?

**Comment by js-ojus** [comment]
Further, continuing the above scenario, there is another issue to deal with.

After adding the second group, suppose that I delete the first group.  Now, we need a mechanism to determine that the common user of both groups should **not** be removed, because of membership in the second group.

**Comment by js-ojus** [comment]
This has been solved by changing the hierarchy from users to groups.
